package uk.gov.justice.digital.hmpps.manageoffencesapi.enum

enum class Feature {
  FULL_SYNC_NOMIS,
  DELTA_SYNC_NOMIS,
  FULL_SYNC_SDRS,
  DELTA_SYNC_SDRS,
  SYNC_HOME_OFFICE_CODES,
  PUBLISH_EVENTS,
  UNLINK_SCHEDULES_NOMIS,
  LINK_SCHEDULES_NOMIS,
  T3_OFFENCE_EXCLUSIONS,
}
