---
# Per environment values which override defaults in manage-offences-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-offences-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    # TODO Update API_BASE_URL_SDRS with the test service URL (currently unknown)
    API_BASE_URL_SDRS: http://localhost:8332

  # Switches off the allowlist in the DEV env only.
  allowlist: null

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
