-- Schedule 1 Part 1 mappings paragraphs 1 to 3
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to Common Law', (SELECT id FROM offence WHERE code = 'COML025'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'COML025A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to section 1(1) of the Criminal Law Act 1977.', (SELECT id FROM offence WHERE code = 'COML025C'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to Common Law.', (SELECT id FROM offence WHERE code = 'COML026'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'COML026A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 1), 'Contrary to section 1(1) of the Criminal Law Act 1977.', (SELECT id FROM offence WHERE code = 'COML026C'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 2), 'Contrary to Common Law.', (SELECT id FROM offence WHERE code = 'COML022'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 2), 'Contrary to Common Law.', (SELECT id FROM offence WHERE code = 'COML023'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 3), 'Contrary to Common Law.', (SELECT id FROM offence WHERE code = 'COML020'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 3), 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'COML020A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 3), 'Contrary to section 1(1) of the Criminal Law Act 1977.', (SELECT id FROM offence WHERE code = 'COML020C'));

-- Schedule 1 Part 1 mappings paragraph 4
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'a', 'Contrary to section 4 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'a', 'Contrary to section 1 of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'OF61003A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 18 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61016'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'OF61016A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 18 of the Offences Against the Person Act 1861 and section 8 of the Accessories and Abettors Act 1861.', (SELECT id FROM offence WHERE code = 'OF61016B'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 18 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61017'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'OF61017A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 1(1) of the Criminal Law Act 1977.', (SELECT id FROM offence WHERE code = 'OF61017C'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 18 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61018'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'b', 'Contrary to section 18 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61019'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'c', 'Contrary to section 23 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61060'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'c', 'Contrary to section 1(1) of the Criminal Law Act 1977.', (SELECT id FROM offence WHERE code = 'OF61060C'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'd', 'Contrary to section 28 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61050'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61051'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61058'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61059'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61063'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61073'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61074'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61075'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61076'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61128'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61129'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'e', 'Contrary to section 29 of the Offences Against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61130'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'f', 'Contrary to section 64 of the Offences against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61115'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 4), 'f', 'Contrary to section 64 of the Offences against the Person Act 1861.', (SELECT id FROM offence WHERE code = 'OF61116'));

-- Schedule 1 Part 1 mappings paragraph 5
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'a', 'Contrary to section 2 of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83026'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'b', 'Contrary to section 3(1)(a) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83028'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'b', 'Contrary to section 3(1)(b) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83029'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'b', 'Contrary to section 1(1) of the Criminal Attempts Act 1981.', (SELECT id FROM offence WHERE code = 'EX83029A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'b', 'Contrary to section 3(1)(b) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83030'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'c', 'Contrary to section 4(1) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83009'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'c', 'Contrary to section 4(1) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83010'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'c', 'Contrary to section 1(1) of the Criminal Attempts Act 1981 and section 4(1) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83010A'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 5), 'c', 'Contrary to section 1(1) of the Criminal Law Act 1977 and section 4(1) of the Explosive Substances Act 1883.', (SELECT id FROM offence WHERE code = 'EX83010C'));

-- Schedule 1 Part 1 mappings paragraph 7
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 7), 'Contrary to section 1 of the Taking of Hostages Act 1982.', (SELECT id FROM offence WHERE code = 'TH82001'));

-- Schedule 1 Part 1 mappings paragraphs 8 and 10
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'a', 'Contrary to section 1 of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82001'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'b', 'Contrary to Section 2(1)(a) and (5) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82002'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'b', 'Contrary to Section 2(1)(a) and (5) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'b', 'Contrary to Section 2(1)(b) and (5) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82004'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'b', 'Contrary to Section 2(2) and (5) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82069'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'c', 'Contrary to section 3(3) and (7) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82011'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'c', 'Contrary to section 3(1) and (7) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82070'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'd', 'Contrary to section 4(1)(a), (b), (2) and (4) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82012'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'd', 'Contrary to section 4(1)(c), (2) and (4) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82013'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'd', 'Contrary to section 4(1)(d), (2) and (4) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82014'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 8), 'e', 'Contrary to section 6(2) and (3) of the Aviation Security Act 1982.', (SELECT id FROM offence WHERE code = 'AV82071'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'a', 'Contrary to section 1(1) and (5) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'b', 'Contrary to section 9(1) and (3) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90013'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'c', 'Contrary to section 10(1) and (2) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90014'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90015'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90016'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90017'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90018'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90019'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90020'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(c) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90021'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(1)(c) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90022'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90023'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90024'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90025'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90026'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90027'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90028'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90029'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90030'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90031'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(a) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90032'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90033'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'd', 'Contrary to section 11(2)(b) and (6) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90034'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'e', 'Contrary to section 14(4) and (5) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90041'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 10), 'e', 'Contrary to section 14(4) and (5) of the Aviation and Maritime Security Act 1990.', (SELECT id FROM offence WHERE code = 'AV90042'));

-- Schedule 1 Part 1 mappings paragraph 11
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 4(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94001'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 4(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94002'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 5(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 5(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94004'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(a) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94005'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(a) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94006'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94007'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94008'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94009'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94010'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(c) and (4) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94011'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(1)(c) and (4) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94012'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(2)(a) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94013'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(2)(a) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94014'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(2)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94015'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 6(2)(b) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94016'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 7(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94017'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 7(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94018'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 7(3) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94019'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 8(1) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94020'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 11), 'Contrary to article 8(2) of the Channel Tunnel (Security) Order 1994.', (SELECT id FROM offence WHERE code = 'CT94021'));

-- Schedule 1 Part 1 mappings paragraphs 12 and 13
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 12), 'b', 'Contrary to section 11(1)(e) and (3) of the Chemical Weapons Act 1996.', (SELECT id FROM offence WHERE code = 'CW96036'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 12), 'b', 'Contrary to section 11(1)(f) and (3) of the Chemical Weapons Act 1996.', (SELECT id FROM offence WHERE code = 'CW96037'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 12), 'b', 'Contrary to section 11(1)(g) and (3) of the Chemical Weapons Act 1996.', (SELECT id FROM offence WHERE code = 'CW96038'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 12), 'b', 'Contrary to section 11(1)(h) and (3) of the Chemical Weapons Act 1996.', (SELECT id FROM offence WHERE code = 'CW96039'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(a) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01002'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(b) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(c) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01004'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(d) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01005'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(e) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01006'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(1)(a) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01023'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(1)(b) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01024'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(2) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01025'));
