-- Schedule 1 Part 1 paragraph  13
INSERT INTO schedule_paragraph (schedule_part_id, paragraph_number, paragraph_title) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1), 13, ' Anti-Terrorism, Crime and Security Act 2001');

-- Schedule 1 Part 1 mappings paragraph  13
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(a) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01002'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(b) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01003'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(c) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01004'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(d) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01005'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'a', 'Contrary to section 47(1)(e) and (5) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01006'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(1)(a) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01023'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(1)(b) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01024'));
INSERT INTO offence_schedule_mapping (schedule_paragraph_id, line_reference, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_paragraph WHERE schedule_part_id = (SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = '1') and part_number = 1) and paragraph_number = 13), 'b', 'Contrary to section 114(2) and (3) of the Anti-Terrorism, Crime and Security Act 2001.', (SELECT id FROM offence WHERE code = 'AT01025'));
