ALTER TABLE offence ADD COLUMN revision_id INTEGER;
ALTER TABLE offence ADD COLUMN cjs_title VARCHAR(1024);
ALTER TABLE offence ADD COLUMN start_date DATE;
ALTER TABLE offence ADD COLUMN end_date DATE;
ALTER TABLE offence ADD COLUMN changed_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE offence ADD COLUMN created_date TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE offence ADD COLUMN last_updated_date TIMESTAMP WITH TIME ZONE NOT NULL;
