INSERT INTO schedule (act, code)
VALUES ('Domestic Violence Excluded Offences', 'DVEO');

INSERT INTO schedule_part (schedule_id, part_number) VALUES ((SELECT id FROM schedule WHERE code = 'DVEO'), 1);

-- Dropping the constraints for the integration tests, are re-enabled after the inserts (this is not necessary for the real environments as all the expected offences exist)
ALTER TABLE offence_schedule_mapping DROP CONSTRAINT fk_schedule_to_offence_constraint;
ALTER TABLE offence_schedule_mapping ALTER COLUMN offence_id DROP NOT NULL;

INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CD98077'),(SELECT id FROM offence WHERE code = 'CD98077'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CD98078'),(SELECT id FROM offence WHERE code = 'CD98078'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CD98079'),(SELECT id FROM offence WHERE code = 'CD98079'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CD98080'),(SELECT id FROM offence WHERE code = 'CD98080'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CD98081'),(SELECT id FROM offence WHERE code = 'CD98081'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CS10503'),(SELECT id FROM offence WHERE code = 'CS10503'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'FL96001'),(SELECT id FROM offence WHERE code = 'FL96001'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'FL96001A'),(SELECT id FROM offence WHERE code = 'FL96001A'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97003A'),(SELECT id FROM offence WHERE code = 'PH97003A'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97006'),(SELECT id FROM offence WHERE code = 'PH97006'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97007'),(SELECT id FROM offence WHERE code = 'PH97007'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97008'),(SELECT id FROM offence WHERE code = 'PH97008'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97010'),(SELECT id FROM offence WHERE code = 'PH97010'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97011'),(SELECT id FROM offence WHERE code = 'PH97011'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PH97011B'),(SELECT id FROM offence WHERE code = 'PH97011B'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SC15004'),(SELECT id FROM offence WHERE code = 'SC15004'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SC15005'),(SELECT id FROM offence WHERE code = 'SC15005'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SC15005A'),(SELECT id FROM offence WHERE code = 'SC15005A'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SC15006'),(SELECT id FROM offence WHERE code = 'SC15006'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SC15006A'),(SELECT id FROM offence WHERE code = 'SC15006A'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SE20002'),(SELECT id FROM offence WHERE code = 'SE20002'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'DVEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'SE20002A'),(SELECT id FROM offence WHERE code = 'SE20002A'));

DELETE FROM offence_schedule_mapping WHERE offence_id IS NULL;

ALTER TABLE offence_schedule_mapping ADD CONSTRAINT fk_schedule_to_offence_constraint FOREIGN KEY (offence_id) REFERENCES offence(id);
ALTER TABLE offence_schedule_mapping ALTER COLUMN offence_id SET NOT NULL;
