INSERT INTO schedule (act, code)
VALUES ('Terrorism Excluded Offences', 'TEO');

INSERT INTO schedule_part (schedule_id, part_number) VALUES ((SELECT id FROM schedule WHERE code = 'TEO'), 1);

-- Dropping the constraints for the integration tests, are re-enabled after the inserts (this is not necessary for the real environments as all the expected offences exist)
ALTER TABLE offence_schedule_mapping DROP CONSTRAINT fk_schedule_to_offence_constraint;
ALTER TABLE offence_schedule_mapping ALTER COLUMN offence_id DROP NOT NULL;

INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CT15003'),(SELECT id FROM offence WHERE code = 'CD98077'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CT15004'),(SELECT id FROM offence WHERE code = 'CT15003'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CT19001'),(SELECT id FROM offence WHERE code = 'CT15004'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'CT19002'),(SELECT id FROM offence WHERE code = 'CT19001'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PL02027'),(SELECT id FROM offence WHERE code = 'CT19002'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PL02028'),(SELECT id FROM offence WHERE code = 'PL02027'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PL02029'),(SELECT id FROM offence WHERE code = 'PL02028'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PL02030'),(SELECT id FROM offence WHERE code = 'PL02029'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00009'),(SELECT id FROM offence WHERE code = 'PL02030'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00010'),(SELECT id FROM offence WHERE code = 'PT00009'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00011'),(SELECT id FROM offence WHERE code = 'PT00010'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00012'),(SELECT id FROM offence WHERE code = 'PT00011'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00008'),(SELECT id FROM offence WHERE code = 'PT00012'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00027'),(SELECT id FROM offence WHERE code = 'PT00008'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00028'),(SELECT id FROM offence WHERE code = 'PT00027'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00071'),(SELECT id FROM offence WHERE code = 'PT00028'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00051'),(SELECT id FROM offence WHERE code = 'PT00071'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00052'),(SELECT id FROM offence WHERE code = 'PT00051'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00053'),(SELECT id FROM offence WHERE code = 'PT00052'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00054'),(SELECT id FROM offence WHERE code = 'PT00053'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00055'),(SELECT id FROM offence WHERE code = 'PT00054'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00058'),(SELECT id FROM offence WHERE code = 'PT00055'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00059'),(SELECT id FROM offence WHERE code = 'PT00058'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00060'),(SELECT id FROM offence WHERE code = 'PT00059'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00061'),(SELECT id FROM offence WHERE code = 'PT00060'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'PT00062'),(SELECT id FROM offence WHERE code = 'PT00061'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'TR08013'),(SELECT id FROM offence WHERE code = 'PT00062'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'TR08014'),(SELECT id FROM offence WHERE code = 'TR08013'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'TR08015'),(SELECT id FROM offence WHERE code = 'TR08014'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'TR08017'),(SELECT id FROM offence WHERE code = 'TR08015'));
INSERT INTO offence_schedule_mapping (schedule_part_id, legislation_text, offence_id) VALUES ((SELECT id FROM schedule_part WHERE schedule_id =  (SELECT id FROM schedule WHERE code = 'TEO') and part_number = 1),(SELECT acts_and_sections FROM offence WHERE code = 'TR08016'),(SELECT id FROM offence WHERE code = 'TR08017'));

DELETE FROM offence_schedule_mapping WHERE offence_id IS NULL;

ALTER TABLE offence_schedule_mapping ADD CONSTRAINT fk_schedule_to_offence_constraint FOREIGN KEY (offence_id) REFERENCES offence(id);
ALTER TABLE offence_schedule_mapping ALTER COLUMN offence_id SET NOT NULL;
