INSERT INTO offence (code,
                     description,
                     revision_id,
                     cjs_title,
                     start_date,
                     end_date,
                     changed_date,
                     created_date,
                     last_updated_date,
                     category,
                     sub_category,
                     acts_and_sections,
                     parent_offence_id,
                     offence_type,
                     max_period_is_life,
                     max_period_of_indictment_years,
                     max_period_of_indictment_weeks,
                     max_period_of_indictment_days,
                     max_period_of_indictment_months,
                     sdrs_cache)
VALUES (
        'CD98074E',
        'Encouragement to Racially / religiously aggravated criminal damage - terrorism',
        612585,
        'Encouragement to Racially / religiously aggravated criminal damage - terrorism',
        '2015-03-12',
        NULL,
        NOW(),
        NOW(),
        NOW(),
        58,
        4,
        'Contrary to section 30(1) and (2) of the Crime and Disorder Act 1998. Also contrary to sections 44 and 58 of the Serious Crimes Act 2007',
        (SELECT id FROM offence WHERE code = 'CD98074'),
        'CI',
        false,
        14,
        NULL,
        NULL,
        NULL,
        'OFFENCES_A');
