DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'actuarial_flag') THEN
        CREATE TYPE actuarial_flag AS ENUM (
                            'OPD_VIOLENCE_SEX_FLAG',
                            'IS_VIOLENT_SANCTION'
        );
    END IF;
END $$;

ALTER TABLE risk_actuarial_ho_code_flags
    ALTER COLUMN flag_name TYPE actuarial_flag
    USING flag_name::actuarial_flag;

ALTER TABLE risk_actuarial_ho_code
    ALTER COLUMN parent_group_description TYPE text,
    ALTER COLUMN category_description TYPE text,
    ALTER COLUMN sub_category_description TYPE text;

INSERT INTO risk_actuarial_ho_code_category (category_name, created_date) VALUES
    ('UNKNOWN', CURRENT_TIMESTAMP),
    ('BURGLARY_DOMESTIC', CURRENT_TIMESTAMP),
    ('BURGLARY_OTHER', CURRENT_TIMESTAMP),
    ('DRUNKENNESS', CURRENT_TIMESTAMP),
    ('DRINK_DRIVING', CURRENT_TIMESTAMP),
    ('MOTORING_OFFENCES', CURRENT_TIMESTAMP),
    ('VEHICLE_RELATED_THEFT', CURRENT_TIMESTAMP),
    ('FRAUD_AND_FORGERY', CURRENT_TIMESTAMP),
    ('WELFARE_FRAUD', CURRENT_TIMESTAMP),
    ('DRUG_IMPORT_EXPORT_OR_PRODUCTION', CURRENT_TIMESTAMP),
    ('DRUG_POSSESSION_OR_SUPPLY', CURRENT_TIMESTAMP),
    ('VIOLENCE_AGAINST_THE_PERSON_ABH_PLUS', CURRENT_TIMESTAMP),
    ('VIOLENCE_AGAINST_THE_PERSON_SUB_ABH', CURRENT_TIMESTAMP),
    ('PUBLIC_ORDER_AND_HARRASSMENT', CURRENT_TIMESTAMP),
    ('WEAPONS_NON_FIREARM', CURRENT_TIMESTAMP),
    ('FIREARMS_MOST_SERIOUS', CURRENT_TIMESTAMP),
    ('FIREARMS_OTHER', CURRENT_TIMESTAMP),
    ('HANDLING_STOLEN_GOODS', CURRENT_TIMESTAMP),
    ('CRIMINAL_DAMAGE', CURRENT_TIMESTAMP),
    ('ACQUISITIVE_VIOLENCE', CURRENT_TIMESTAMP),
    ('OTHER_OFFENCES', CURRENT_TIMESTAMP),
    ('ABSCONDING_OR_BAIL', CURRENT_TIMESTAMP),
    ('SEXUAL_AGAINST_CHILD', CURRENT_TIMESTAMP),
    ('SEXUAL_NOT_AGAINST_CHILD', CURRENT_TIMESTAMP),
    ('THEFT_NON_MOTOR', CURRENT_TIMESTAMP),
